services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    container_name: chat_server
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres
    container_name: postgres_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data: